export const GET_RESISTER_LOADING = 'GET_RESISTER_LOADING'
export const GET_RESISTER_SUCCESS = 'GET_RESISTER_SUCCESS'
export const GET_RESISTER_ERROR = 'GET_RESISTER_ERROR'

export const GET_LOGIN_LOADING = 'GET_LOGIN_LOADING'
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'
export const GET_LOGIN_ERROR = 'GET_LOGIN_ERROR'


export const GET_LOGOUT = 'GET_LOGOUT'

export const GET_STATUS_LOADING = 'GET_STATUS_LOADING'
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS'
export const GET_STATUS_ERROR = 'GET_STATUS_ERROR'
